---
- name: Installing nginx & start service
  hosts: webserver
  become: true

  tasks:
  - name: install nginx
    yum:
      name: nginx
      state: latest

  - name: start nginx
    service:
      name: nginx
      state: started

